name: Rust

on:
  push:
    branches: [ main ]

jobs:
  build_linux_windows:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install cross
        run: cargo install cross

      - name: Build for Linux
        run: cross build --target x86_64-unknown-linux-gnu --release --bin mongo_data_exporter
      - name: Move Linux binary to bin
        run: |
          mkdir -p bin
          mv target/x86_64-unknown-linux-gnu/release/mongo_data_exporter bin/mongo_data_exporter_linux

      - name: Build for Windows
        run: cross build --target x86_64-pc-windows-gnu --release --bin mongo_data_exporter
      - name: Move Windows binary to bin
        run: |
          mv target/x86_64-pc-windows-gnu/release/mongo_data_exporter.exe bin/mongo_data_exporter_windows.exe

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: bin/

  build_mac:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        run: cargo build --release --bin mongo_data_exporter

      - name: Move to bin
        run: |
          mkdir -p bin
          mv target/release/mongo_data_exporter bin/mongo_data_exporter_mac

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: binaries_mac
          path: bin/